export const ImagePath = {
  dropdownTriangle: require('./assets/images/ic_dropdown.png'),
  fb: require('./assets/images/fb.png'),
  phone: require('./assets/images/phone.png'),
  google: require('./assets/images/google_ic.png'),
  insta: require('./assets/images/ic_insta.png'),
  apple: require('./assets/images/apple.png'),
  back: require('./assets/images/ic_back.png'),
  backWithSquare: require('./assets/images/backWithSquare.png'),
  rightBlue: require('./assets/images/ic_goA.png'),

  rightArrow: require('./assets/images/Vector.png'),
  leftArrow: require('./assets/images/leftArrow.png'),
  eyeIcon: require('./assets/images/eyeIcon.png'),
  hidePassword: require('./assets/images/hidePasword.png'),
  radioEmpty: require('./assets/images/radioEmpty.png'),
  radioFilled: require('./assets/images/radioCheckd.png'),
  email: require('./assets/images/email.png'),
  instagram: require('./assets/images/instagram.png'),
  photoPick: require('./assets/images/photoPick.png'),
  location: require('./assets/images/Location.png'),
  
  crossIcon: require('./assets/images/crossIcon.png'),
  messageIcon: require('./assets/images/messageIcon.png'),
  ready: require('./assets/images/Ready.png'),
  rightArrowGray: require('./assets/images/rightArrowgray.png'),

  //tab bar icons
  feed:require('./assets/images/Feed.png'),
  chat:require('./assets/images/chat.png'),
  search:require('./assets/images/search.png'),
  profile:require('./assets/images/Profile.png'),
  upload:require('./assets/images/upload_focus.png'),
  uploadFocus:require('./assets/images/uploadFocuss.png'),

  notification:require('./assets/images/notification.png'),
  product1:require('./assets/images/product1.png'),
  product2:require('./assets/images/product2.png'),
  brandImg:require('./assets/images/brandImg.png'),
  heart:require('./assets/images/heart.png'),

  ic_cross:require('./assets/images/ic_cross.png'),
  filter:require('./assets/images/filter.png'),
  horizontalLine:require('./assets/images/horizontalLine.png'),
  downArrow:require('./assets/images/downArrow.png'),
  options:require('./assets/images/options.png'),
  horizontalLine2: require('./assets/images/horizontalLine2.png'),

  //Profile Screen
  optionsBlack:require('./assets/images/optionsBlack.png'),
  smallVerticalLine:require('./assets/images/smallVerticalLine.png'),
  verticalLine:require('./assets/images/verticalLine.png'),
  followersView:require('./assets/images/followersView.png'),

  share:require('./assets/images/share.png'),
  heartFilled:require('./assets/images/heartFilled.png'),
  pro:require('./assets/images/Pro.png'),
  stats:require('./assets/images/stats.png'),
  edit:require('./assets/images/edit.png'),
  settings:require('./assets/images/settings.png'),
  logout:require('./assets/images/logout.png'),
  horizontalLineOpt:require('./assets/images/horizontalLineOpt.png'),

  ic_next:require('./assets/images/ic_next.png'),
  instaUrl:require('./assets/images/insta_logo.png'),
  snapchat:require('./assets/images/snapchat_logo.png'),
  youtube:require('./assets/images/youtube_logo.png'),

  serum:require('./assets/images/serum.png'),
  handWave:require('./assets/images/handWave.png'),

  ic_insta:require('./assets/images/insta_ic.png'),
  ic_youtube:require('./assets/images/youtube_ic.png'),
  ic_tiktok:require('./assets/images/tiktok_ic.png'),
  ic_snapchat:require('./assets/images/snapchat_ic.png'),

  rightSlide:require('./assets/images/Group216.png'),
  leftSlide:require('./assets/images/Group214.png'),
  ic_upward:require('./assets/images/ic_upward.png'),
  ic_crosss:require('./assets/images/ic_crosss.png'),
  remove:require('./assets/images/remove.png'),
  tiktok:require('./assets/images/tiktok_logo.png'),
  toggleOff:require('./assets/images/toggleOff.png'),
  toggleOn:require('./assets/images/toggleOn.png'),

  ic_gender:require('./assets/images/ic_gender.png'),
  ic_downArrow:require('./assets/images/ic_downArrow.png'),
  arrowBack:require('./assets/images/arrowBack.png'),
  ic_check:require('./assets/images/ic_check.png'),
  heartFillBlack:require('./assets/images/heartFillBlack.png'),
  optGrey:require('./assets/images/optGrey.png'),
  priceRange:require('./assets/images/priceRange.png'),

  profilePlace:require('./assets/images/dpHolder.png'),
  cameraIcon:require('./assets/images/cameraIcon.png'),
  postShadow:require('./assets/images/postShadow.png'),

  ic_location:require('./assets/images/ic_location.png'),
  ic_posted:require('./assets/images/ic_posted.png'),
  ic_ready:require('./assets/images/ic_ready.png'),
  ellipse:require('./assets/images/eliipse.png'),

  insta_select:require('./assets/images/insta_select.png'),
  youtube_select:require('./assets/images/youtube_select.png'),
  snapchat_select:require('./assets/images/snapchat_select.png'),
  tiktok_select:require('./assets/images/tiktok_select.png'),
  multiple:require('./assets/images/multiple.png'),
  arrowRight:require('./assets/images/arrowRight.png'),

  archive:require('./assets/images/archive.png'),
  delete:require('./assets/images/delte.png'),
  unread:require('./assets/images/unread.png'),
  mute:require('./assets/images/notifi.png'),
  report:require('./assets/images/report.png'),

  pickAttach:require('./assets/images/picAttach.png'),
  voice:require('./assets/images/voice.png'),
  stopAudio:require('./assets/images/stopAudio.png'),
  playAudio:require('./assets/images/playAudio.png'),

  matched:require('./assets/images/match.png'),
  imgPlace:require('./assets/images/imgPlace.png'),
  work:require('./assets/images/work.png'),
  workFocus:require('./assets/images/workFocus.png'),
  create:require('./assets/images/create.png'),

  ig_stats:require('./assets/images/ig_stats.png'),
  arrowWhite:require('./assets/images/arrowWhite.png'),
  tiktok_stats:require('./assets/images/tiktok_stats.png'),
  sc_stats:require('./assets/images/sc_stats.png'),
  utube_stats:require('./assets/images/utube_stats.png'),
  archive_camp:require('./assets/images/archive_camp.png'),
  pause:require('./assets/images/pause.png'),
  upArrow:require('./assets/images/up_arrow.png'),
  ic_play:require('./assets/images/ic_play.png'),
  unarchive:require('./assets/images/unarchive.png'),
  profileAdd:require('./assets/images/profileAdd.jpg'),
  iconPlus:require('./assets/images/iconPlus.png'),
  unarchive_ic:require('./assets/images/unarchive_ic.png'),
};